### PR TITLE
give a module name

### PR DESCRIPTION
**Pull request by hajimehoshi**
This PR gives a module name for the example so that we can execute the example like this:

```sh
go run github.com/wailsapp/examples/default_no_question_dialog@latest
```

### CODE REVIEW

**Comment by hajimehoshi** [comment]
I found this error when `go run .` in this project:

```
main.go:10:12: pattern all:frontend/dist: no matching files found
```

How can I execute this?

**Comment by leaanthony** [comment]
Wails does not support `go run`. Build it using `wails build`.

**Comment by hajimehoshi** [comment]
I saw the same error with `go run github.com/wailsapp/wails/v2/cmd/wails@latest build .`. Thanks

**Comment by leaanthony** [comment]
Wails does not support `go run`. Build it using `wails build`.

**Comment by hajimehoshi** [comment]
Right, so I executed wails command via go run.

**Comment by hajimehoshi** [comment]
I will try go-installing wails and running it later but I believe the result is the same as above.

**Comment by leaanthony** [comment]
Please create an issue if you find there is a problem 👍 
Would be awesome to find out if ebitengine webassembly could be run in Wails 😄

**Pull request merged**
